const staff = [
	{
		id: 1,
		position: 'Партнер',
		avatar: '/artur.png',
		email: "artur.fields@reqres.in",
		first_name: "Артур",
		last_name: "Королев",
		liked: false,
		tel: "89111234578",
		morePartOne: 'Клиенты видят в нем эксперта по вопросам разработки комплексных решений финансовых продуктов, включая такие аспекты, как организационная структура, процессы, аналитика и ИТ-компоненты. Он помогает клиентам лучше понимать структуру рисков их бизнеса, улучшать процессы за счет применения новейших технологий и увеличивать продажи, используя самые современные аналитические инструменты.',
		morePartTwo: 'В работе с клиентами недостаточно просто решить конкретную проблему или помочь справиться с трудностями.Не менее важно уделять внимание обмену знаниями: "Один из самых позитивных моментов — это осознание того, что ты помог клиенту перейти на совершенно новый уровень компетентности, уверенность в том, что после окончания проекта у клиента есть все необходимое, чтобы дальше развиваться самостоятельно"',
		morePartThree: 'Помимо разнообразных проектов для клиентов финансового сектора, Сорин ведет активную предпринимательскую деятельность.Он является совладельцем сети клиник эстетической медицины в Швейцарии, предлагающей инновационный подход к красоте, а также инвестором других бизнес- проектов.',
	},
	{
		id: 2,
		position: 'Партнер',
		avatar: '/olga.png',
		email: "olga.fields@reqres.in",
		first_name: "Ольга",
		last_name: "Ильина",
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem, ex beatae incidunt, repudiandae labore voluptatem et adipisci, quis molestias id debitis illo itaque autem explicabo! Consequatur, vero! Ea, dicta at!',
		morePartTwo: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Architecto optio dicta reiciendis, vel quod reprehenderit sint enim aperiam, tempore explicabo possimus voluptatem aliquam perspiciatis tenetur, quibusdam voluptas ullam error eum.',
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum.',
	},
	{
		id: 3,
		avatar: '/zamir.png',
		email: "zamir.fields@reqres.in",
		first_name: "Замир",
		last_name: "Орлов",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure!', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus.' ,
	},
	{
		id: 4,
		avatar: '/daniil.png',
		email: "daniil.fields@reqres.in",
		first_name: "Даниил",
		last_name: "Новиков",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure!', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus.' ,
	},
	{
		id: 5,
		avatar: '/diana.png',
		email: "diana.fields@reqres.in",
		first_name: "Дарья",
		last_name: "Семенова",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure!', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.' , 
	},
	{
		id: 6,
		avatar: '/zahar.png',
		email: "zahar.fields@reqres.in",
		first_name: "Захар",
		last_name: "Романов",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
	{
		id: 7,
		avatar: '/egor.png',
		email: "egor.fields@reqres.in",
		first_name: "Егор",
		last_name: "Волков",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
	{
		id: 8,
		avatar: '/kira.png',
		email: "kira.fields@reqres.in",
		first_name: "Кира",
		last_name: "Попова",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
	{
		id: 9,
		avatar: '/diana.png',
		email: "diana2.fields@reqres.in",
		first_name: "Диана",
		last_name: "Андреева",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
	{
		id: 10,
		avatar: '/zahar.png',
		email: "zahar2.fields@reqres.in",
		first_name: "Захар",
		last_name: "Романов",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
	{
		id: 11,
		avatar: '/egor.png',
		email: "egor2.fields@reqres.in",
		first_name: "Егор",
		last_name: "Волков",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
	{
		id: 12,
		avatar: '/kira.png',
		email: "kira2.fields@reqres.in",
		first_name: "Кира",
		last_name: "Попова",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
	{
		id: 13,
		avatar: "https://reqres.in/img/faces/7-image.jpg",
		email: "michael.lawson@reqres.in",
		first_name: "Michael",
		last_name: "Lawson",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
	{
		id: 14,
		avatar: "https://reqres.in/img/faces/8-image.jpg",
		email: "lindsay.ferguson@reqres.in",
		first_name: "Lindsay",
		last_name: "Lawson",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
	{
		id: 15,
		avatar: "https://reqres.in/img/faces/9-image.jpg",
		email: "tobias.funke@reqres.in",
		first_name: "Tobias",
		last_name: "Funke",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
	{
		id: 16,
		avatar: "https://reqres.in/img/faces/10-image.jpg",
		email: "byron.fields@reqres.in",
		first_name: "Byron",
		last_name: "Fields",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
	{
		id: 17,
		avatar: "https://reqres.in/img/faces/11-image.jpg",
		email: "george.edwards@reqres.in",
		first_name: "George",
		last_name: "Edwards",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Клиенты видят в нем эксперта по вопросам разработки комплексных решений финансовых продуктов, включая такие аспекты, как организационная структура, процессы, аналитика и ИТ-компоненты. Он помогает клиентам лучше понимать структуру рисков их бизнеса, улучшать процессы за счет применения новейших технологий и увеличивать продажи, используя самые современные аналитические инструменты.',
		morePartTwo: 'В работе с клиентами недостаточно просто решить конкретную проблему или помочь справиться с трудностями.Не менее важно уделять внимание обмену знаниями: "Один из самых позитивных моментов — это осознание того, что ты помог клиенту перейти на совершенно новый уровень компетентности, уверенность в том, что после окончания проекта у клиента есть все необходимое, чтобы дальше развиваться самостоятельно"',
		morePartThree: 'Помимо разнообразных проектов для клиентов финансового сектора, Сорин ведет активную предпринимательскую деятельность.Он является совладельцем сети клиник эстетической медицины в Швейцарии, предлагающей инновационный подход к красоте, а также инвестором других бизнес- проектов.',
	},
	{
		id: 18,
		avatar: "https://reqres.in/img/faces/12-image.jpg",
		email: "rachel.howell@reqres.in",
		irst_name: "Rachel",
		last_name: "Howell",
		position: 'Партнер',
		liked: false,
		tel: "89111234578",
		morePartOne: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim pariatur vitae nostrum aspernatur at, facilis repellendus hic tempore quas in eos officia dolorem dicta. Voluptas facilis cum consequuntur cumque alias? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam labore veniam velit aut similique quod a quasi earum ducimus porro. Itaque hic nobis, neque omnis ipsam in tenetur atque commodi?', 
		morePartTwo: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quae excepturi, deserunt expedita magnam delectus, et accusamus ad quam, quisquam a rem. Ullam deleniti in libero cum tenetur quisquam iure! Odit quas eligendi inventore suscipit nulla ratione quis illum amet? Recusandae iure laborum doloribus quas, aliquid quod similique. Dolorem dignissimos magnam voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ut, dolores rerum consectetur velit, amet est nostrum, dolorum quia veritatis ad? Exercitationem dolorem blanditiis nisi quasi fuga natus nam alias.', 
		morePartThree: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae quod porro nesciunt, blanditiis eum odio dolorem doloribus consequatur! Sint itaque obcaecati deserunt unde sapiente accusantium repellendus libero possimus voluptatem illum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. ' , 
	},
]

export default staff;